version: 2
jobs:
  build:
    docker:
      - image: node:6-alpine
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  # deploy-to-prod-job:
  #   steps:
  #     - checkout
  #     - run
  #       name: Install dependencies
  #       command: |
  #         apt-get -y -qq update
  #         apt-get -y -qq install python3.4-dev
  #         curl -O https://bootstrap.pypa.io/get-pip.py
  #         python3.4 get-pip.py --user
  #         pip install awscli --upgrade --user
  #         aws s3 sync /build s3://nicoapples.com/build --delete

# workflows:
#   version: 2
#   build_deploy:
#     jobs:
#       - test
#       - build
#         requires:
#           - test
#         filters:
#           branches:
#             only: master
      # - deploy-to-prod-job:
      #     requires:
      #       - build-job
      #     filters:
      #       branches:
      #         only: master
