version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run build

  deploy-job:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sudo apt-get -y -qq update
      - run: sudo apt-get -y -qq install python3.4-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python3.4 get-pip.py --user
      - run: sudo pip install awscli --upgrade --user
      - run: aws s3 sync /build s3://nicoapples.com/build --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
